# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rng.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rng.proto',
  package='rng',
  syntax='proto3',
  serialized_options=b'\252\002\007RNGesus',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\trng.proto\x12\x03rng\".\n\nRngRequest\x12\x10\n\x08rngCount\x18\x01 \x01(\x05\x12\x0e\n\x06rngMax\x18\x02 \x01(\x05\"\x1b\n\x08RngReply\x12\x0f\n\x07numbers\x18\x01 \x03(\x05\x32<\n\x07Rngesus\x12\x31\n\x0fGenerateNumbers\x12\x0f.rng.RngRequest\x1a\r.rng.RngReplyB\n\xaa\x02\x07RNGesusb\x06proto3'
)




_RNGREQUEST = _descriptor.Descriptor(
  name='RngRequest',
  full_name='rng.RngRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rngCount', full_name='rng.RngRequest.rngCount', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rngMax', full_name='rng.RngRequest.rngMax', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=64,
)


_RNGREPLY = _descriptor.Descriptor(
  name='RngReply',
  full_name='rng.RngReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='numbers', full_name='rng.RngReply.numbers', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['RngRequest'] = _RNGREQUEST
DESCRIPTOR.message_types_by_name['RngReply'] = _RNGREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RngRequest = _reflection.GeneratedProtocolMessageType('RngRequest', (_message.Message,), {
  'DESCRIPTOR' : _RNGREQUEST,
  '__module__' : 'rng_pb2'
  # @@protoc_insertion_point(class_scope:rng.RngRequest)
  })
_sym_db.RegisterMessage(RngRequest)

RngReply = _reflection.GeneratedProtocolMessageType('RngReply', (_message.Message,), {
  'DESCRIPTOR' : _RNGREPLY,
  '__module__' : 'rng_pb2'
  # @@protoc_insertion_point(class_scope:rng.RngReply)
  })
_sym_db.RegisterMessage(RngReply)


DESCRIPTOR._options = None

_RNGESUS = _descriptor.ServiceDescriptor(
  name='Rngesus',
  full_name='rng.Rngesus',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=95,
  serialized_end=155,
  methods=[
  _descriptor.MethodDescriptor(
    name='GenerateNumbers',
    full_name='rng.Rngesus.GenerateNumbers',
    index=0,
    containing_service=None,
    input_type=_RNGREQUEST,
    output_type=_RNGREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RNGESUS)

DESCRIPTOR.services_by_name['Rngesus'] = _RNGESUS

# @@protoc_insertion_point(module_scope)
